### ISSUE TITLE
[Suggestion/Bug] Make your code path agnostic

### ISSUE THREAD

**Issue by Lusiiky** [Krysiek/CuteDancer#10]
Hello,

I noticed while using your script that if I move the "CuteDancer" folder somewhere else, the script breaks.

It would be nice to fetch the resources in your code with relative paths and not absolute ones.

**Examples:**
![image](https://user-images.githubusercontent.com/29005043/216693217-6348af45-6c7f-41d9-8d06-cc42e7dc4400.png)
By the way, the path to the default Action controller isn't even correct anymore due to the new Creator Companion that moved all the VRCSDK files to the Packages.

![image](https://user-images.githubusercontent.com/29005043/216693909-5ef075b2-e7ff-4fbd-bf7f-6c4d5f38a577.png)
Prefabs paths.

Thank you,
Lusiiky

**Comment by Krysiek** [comment]
Hello,

Thank you for your report! I fixed the issue with paths pointing to assets from Assets/VRCSDK directory.

I didn't change CuteDancer paths yet. I'm planning to move the CuteDancer to Packages directory. Until then, I'll leave the issue open.

**Comment by Krysiek** [comment]
Fixed in 4.0.0 
Core files are in Packages, directory for generated files in Assets can be moved (with corresponding .meta file)
