### ISSUE TITLE
Compatibility with GoGoLoco

### ISSUE THREAD

**Issue by AshtonSparx** [Krysiek/CuteDancer#11]
I understand you don't want to continue working on this [till the crashing issue is fixed](https://feedback.vrchat.com/bug-reports/p/1248-vrchat-crashes-when-many-contacts-collide-with-each-other), but this request doesn't ask for additional stuff, just tweaks for the existing stuff. 

I wanted to use this [along side with GoGoLoco](https://booth.pm/en/items/3290806) but i can't because their poses use the same int range as CuteDancer's VRCEmote int range which is problematic.
![image](https://user-images.githubusercontent.com/53165730/233558345-5f23d4d0-3a8c-41f2-ae94-357e39728308.png)

I managed to fully implement it alongside GoGoLoco till I realized the VRCEmote ints being the same.

**Comment by Krysiek** [comment]
Hello,

Thank you for your report. I've heard about the issue with GoGoLoco but no one told me what is wrong.

I'm currently working on rewriting of installation script with the new UI and for sure include an option to change VRCEmote starting number for CuteDancer.

**Comment by AshtonSparx** [comment]
Sounds good to me! I would recommend looking at what ints GoGoLoco uses to avoid problems, my method of adding it is unorthodox hahaha (I also didn't use the installer because I didn't know there was one)

If you're in the [GoGoLoco discord](https://discord.gg/gogo-loco-911793727633260544), [you can follow my journey here](https://discord.com/channels/911793727633260544/1098680494268362897)

**Comment by AshtonSparx** [comment]
> Hello,
> 
> Thank you for your report. I've heard about the issue with GoGoLoco but no one told me what is wrong.
> 
> I'm currently working on rewriting of installation script with the new UI and for sure include an option to change VRCEmote starting number for CuteDancer.

[https://feedback.vrchat.com/bug-reports/p/1248-vrchat-crashes-when-many-contacts-collide-with-each-other](https://feedback.vrchat.com/bug-reports/p/1248-vrchat-crashes-when-many-contacts-collide-with-each-other) the issue has been fixed apparently! :D and is being released in a future update

**Comment by Krysiek** [comment]
Fixed in 4.0.0
Now you can change parameter name and/or parameter index for CuteDancer build. In case of any problem use different parameter name or index that is not shared with GoGoLoco animations.
