### ISSUE TITLE
GoGoLoco poses are all just T-poses

### ISSUE THREAD

**Issue by AstroDaFloof** [Krysiek/CuteDancer#12]
So I added Cute Dancer with the setup and I also added gogo loco with VRC Fury to my avatar. This caused both of them to not work anymore (All dances are just T-poses and all GoGo Loco poses are also just T-poses). I have almost zero experience with Unity or VRC Avatar creation so I have no idea what could be causing these issues.

**Comment by Krysiek** [comment]
In the new version 4.0.0 you can change parameter name or parameter index used by CuteDancer. You can change these values to not collide with GoGoLoco.
