### ISSUE TITLE
Possible Unity 2022/android issue

### ISSUE THREAD

**Issue by Docteh** [Krysiek/CuteDancer#14]
Hi, I tried using CuteDancer with Unity 2022 today, the PC version uploaded fine, but the Quest version got glitched, no errors at that point, but when I uploaded the Android version, the PC version turned into an Error robot, and the site did not see that a Android/Quest was uploaded under the imposters section.  

I tried reloading the SDK, didn't work. When I restarted Unity it showed me an error about namespace. Lines 132 and 134 of CuteLayers.cs

Assets\CuteDancer\Editor\AnimatorCloner.cs is guarded with `#if VRC_SDK_VRCSDK3` define, I did such a thing to my copy of Assets\CuteDancer\Editor\CuteLayers.cs

**Comment by Krysiek** [comment]
Version 4.0.0 should be compatible with Unity 2022 and VRChat Creator Companion.
