### ISSUE TITLE
Can't add animator layers

### ISSUE THREAD

**Issue by Haardoo** [Krysiek/CuteDancer#9]
Hello, nice job, but i have a problem on an avatar.

CuteDancer creates action animator but refuse to use it !

Any solution ? Thank you !

**Comment by Krysiek** [comment]
Hello

Are you using it in project managed by CreatorCompanion? If yes, try the new version 3.2.

If it won't help, please post more details about the issue. Screenshots with descriptions would be fine.

**Comment by Krysiek** [comment]
Closed due to lack of details.
